### ISSUE TITLE
Can't get callback example working.

### ISSUE THREAD

**Issue by MrJoy** [bnjjj/node-request-digest#12]
I'm helping a partner with integration that involves accessing a dev environment we run protected by digest auth.  They were having some troubles related to the challenge/response setup.

I'm not much of a Node.js person myself, so I don't know if I'm doing something wrong or not, but the callback example listed [here](https://www.npmjs.com/package/request-digest) doesn't seem to work.  Execution continues past `digestRequest.request(...);` (as determined by putting `console.log` statements around everything, but then... nothing.

On top of that, it appears the underlying `request` module you depend on actually does digest auth, challenge/response, etc.  Specifically, this code actually wound up doing the trick:

```
var request = require('request');
request.get('https://our.internal.domain/', {
  'auth': {
    'user': 'our_dev_username',
    'pass': 'our_dev_password',
    'sendImmediately': false
  }
}, function (error, response, body) {
  console.log('error:', error);
  console.log('statusCode:', response && response.statusCode);
  console.log('body:', body);
});
```

Can you clarify what gap your lib is meant to fill, and maybe guide me on what's wrong with the callback example?

**Comment by bnjjj** [comment]
Hello, my library was primarly created because at this moment this feature isn't implemented in the request module. So I think that now my library doesn't do more than the request module except the support of promise natively for request-digest.

So maybe I can help you though to fix your issue. Can you give me more information about your node version ?

**Comment by MrJoy** [comment]
I tried this on Node v7.0.0.

Given the (working) example code I cited above, I'm unclear what specific functionality isn't implemented in `request`?
