### ISSUE TITLE
Need an option to ignore the port

### ISSUE THREAD

**Issue by sbloedel** [bnjjj/node-request-digest#15]
If the user does not provide a port, I don't want to include the port in the url so I'd love an option.  Here's a sample:
options.url = options.includePort ? `${options.host}:${port}${options.path}` : `${options.host}${options.path}`;

I think what got me is the default port is 80 for http and 443 for https.  My url was https and it bit me.

Perhaps another option is to default the port to 80 for http and 443 for https.

**Comment by mbohgard** [comment]
Same here, took me two hours before I found your comment and got it working. Thank you.

**Comment by bnjjj** [comment]
Ok thank you, I will take it in account. Or if you want to participate to https://hacktoberfest.digitalocean.com feel free to add option and contribute :D

**Comment by bnjjj** [comment]
available in v1.0.13
