### ISSUE TITLE
unable to use ip

### ISSUE THREAD

**Issue by muscleman** [bnjjj/node-request-digest#17]
hi, i'm trying to use http://127.0.0.1

but get a error

                if (paramSplitted.length > 2) {
                                  ^

TypeError: Cannot read property 'length' of null

**Comment by muscleman** [comment]
if (paramSplitted && paramSplitted.length > 2) {

**Comment by bnjjj** [comment]
fix available in v1.0.12

**Comment by RogerHardiman** [comment]
I had the same problem.
I was trying to parse this digest header from a HikVision CCTV device (a Analogue Camera IP Encoder, model 6704)

`Digest realm="DVS", domain="DVRDVS",qop="auth", nonce="441bc1c9e01a28185b5fa718c4ad811d", opaque="5ccc069c403ebaf9f0171e9517f40e41",algorithm="MD5", stale="FALSE", Basic realm="DVS"
`

Notice how there is a Digest Realm and also a Basic Realm.
The old version of this library failed to parse the `Basic realm="DVS"` part.

Anyway the latest version (1.0.13) fixes it.
Thanks for the fix.
