### ISSUE TITLE
'response is empty' error

### ISSUE THREAD

**Issue by anoopemacs** [bnjjj/node-request-digest#7]
I am trying the example code, getting 'response is empty' error
https://runkit.com/anoopemacs/bnjjj

```
var digestRequest = require('request-digest')('anoop', 'password');

digestRequest.request({
  host: 'https://sync6.omnigroup.com',
  path: '/anoop/OmniFocus.ofocus/anoop.txt',
  port: 80,
  method: 'GET'
}, function (error, response, body) {
  if (error) {
    throw error;
  }
  console.log(body);
});
```

The server I am accessing follows https://tools.ietf.org/html/rfc2617

cURL does work:
`curl -x $HTTP_PROXY --digest -u anoop:password -X GET https://sync6.omnigroup.com/anoop/anoop.txt`

**Comment by msreynolds** [comment]
@anoopemacs the correct port is 443 for SSL/HTTPS, it is not port 80.  This fixed my error that sounds similar to yours.
